server:
  port: 9001
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/departmentdb
    username: root
    password: root
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  application:
    name: Department-Service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      deafultZone: http://localhost:8761/eureka/

     
