server:
  port: 0
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/departmentdb
    username: root
    password: root
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  application:
    name: Department-Service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      deafultZone: http://localhost:8761/eureka/
    instance:
    instance-id: ${spring.application.name}-${random.int}
#To generate random port use instance property and set server.port to 0
     
